services:
  mongo_nextgen:
    image: mongo:6.0
    container_name: mongo_nextgen
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - nextgen_net

  database_nextgen:
    build:
      context: ./DBS
    container_name: database_nextgen
    expose:
      - "503"
    depends_on:
      - mongo_nextgen
    networks:
      - nextgen_net
      - proxy_net
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB=${MONGO_DB}
    volumes:
      - ./DBS:/app

networks:
  nextgen_net:
    driver: bridge
  proxy_net:
    external: true

volumes:
  mongo_data: